export const GET_COMMANDS = 'GET_COMMANDS';
export const GET_COMMAND = 'GET_COMMAND';
export const CREATE_COMMAND = 'CREATE_COMMAND';
export const UPDATE_COMMAND = 'UPDATE_COMMAND';
export const PATCH_COMMAND = 'PATCH_COMMAND';
export const DELETE_COMMAND = 'DELETE_COMMAND';
export const CLEAR_UI = 'CLEAR_UI';